import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getUser, listRoles, replaceUserRoles, updateUser, type Role, type User, type UserStatus } from '../../shared/api/usersApi'
import { useAuth } from '../../shared/auth/AuthProvider'
import { canUserAction } from './userPermissions'

export function UserDetailPage() {
  const { userId } = useParams(); const { user: actor } = useAuth(); const canUpdate = canUserAction(actor?.permissions ?? [], 'users:update')
  const [value, setValue] = useState<User | null>(null); const [roles, setRoles] = useState<Role[]>([]); const [displayName, setDisplayName] = useState(''); const [selected, setSelected] = useState<string[]>([])
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!userId) return; let active = true; setLoading(true); void Promise.all([getUser(userId), listRoles()]).then(([loaded, available]) => { if (!active) return; setValue(loaded); setDisplayName(loaded.displayName); setSelected(loaded.roles); setRoles(available.items) }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : 'Unable to load user.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [userId])
  if (!canUserAction(actor?.permissions ?? [], 'users:read')) return <section className="page-content"><h1>Forbidden</h1><p className="alert alert-error">You do not have permission to view users.</p></section>
  if (loading) return <section className="page-content"><p className="muted">Loading user…</p></section>
  if (error || !value) return <section className="page-content"><p className="alert alert-error">{error ?? 'User not found.'}</p><Link to="/app/users">Back to users</Link></section>
  const current = value
  function toggleRole(code: string) { setSelected(current => current.includes(code) ? current.filter(item => item !== code) : [...current, code]) }
  async function saveProfile() { setSaving(true); setError(null); try { const updated = await updateUser(current.id, { displayName, status: current.status }); setValue(updated); setDisplayName(updated.displayName) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to update user.') } finally { setSaving(false) } }
  async function changeStatus(status: UserStatus) { setSaving(true); setError(null); try { const updated = await updateUser(current.id, { status }); setValue(updated) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to update status.') } finally { setSaving(false) } }
  async function saveRoles() { setSaving(true); setError(null); try { const updated = await replaceUserRoles(current.id, selected); setValue(updated); setSelected(updated.roles) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to update roles.') } finally { setSaving(false) } }
  return <section className="page-content"><div className="page-heading"><div><p className="eyebrow">Users</p><h1>{current.displayName}</h1><p className="muted">{current.email}</p></div></div>{error && <p className="alert alert-error">{error}</p>}<div className="card stack-form"><label>Email<input readOnly value={current.email} /></label><label>Display name<input readOnly={!canUpdate} value={displayName} onChange={event => setDisplayName(event.target.value)} /></label><p>Status: <strong>{current.status}</strong></p><p>Created: {new Date(current.createdAt).toLocaleString()}</p><p>Updated: {new Date(current.updatedAt).toLocaleString()}</p>{canUpdate && <div><button type="button" disabled={saving} onClick={() => void saveProfile()}>Save display name</button>{current.status === 'ACTIVE' ? <button type="button" disabled={saving} onClick={() => void changeStatus('DISABLED')}>Disable</button> : <button type="button" disabled={saving} onClick={() => void changeStatus('ACTIVE')}>Activate</button>}</div>}</div><div className="card"><h2>Roles</h2><div className="stack-form">{roles.map(role => <label key={role.code}><input disabled={!canUpdate} type="checkbox" checked={selected.includes(role.code)} onChange={() => toggleRole(role.code)} /> {role.name}</label>)}{canUpdate && <button type="button" disabled={saving || selected.length === 0} onClick={() => void saveRoles()}>Save roles</button>}</div></div><Link to="/app/users">Back to users</Link></section>
}
