import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getUser, listRoles, replaceUserRoles, updateUser, type Role, type User, type UserStatus } from '../../shared/api/usersApi'
import { useAuth } from '../../shared/auth/AuthProvider'
import { canUserAction } from './userPermissions'
import { useUserPreferences } from '../../shared/preferences/UserPreferencesProvider'

export function UserDetailPage() {
  const { userId } = useParams(); const { user: actor } = useAuth(); const { t } = useUserPreferences(); const canUpdate = canUserAction(actor?.permissions ?? [], 'users:update')
  const [value, setValue] = useState<User | null>(null); const [roles, setRoles] = useState<Role[]>([]); const [displayName, setDisplayName] = useState(''); const [selected, setSelected] = useState<string[]>([])
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!userId) return; let active = true; setLoading(true); void Promise.all([getUser(userId), listRoles()]).then(([loaded, available]) => { if (!active) return; setValue(loaded); setDisplayName(loaded.displayName); setSelected(loaded.roles); setRoles(available.items) }).catch(cause => { if (active) setError(cause instanceof Error ? cause.message : t('users.loadError')) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [userId, t])
  if (!canUserAction(actor?.permissions ?? [], 'users:read')) return <section className="page-content"><h1>{t('common.forbidden')}</h1><p className="alert alert-error">{t('users.permissionView')}</p></section>
  if (loading) return <section className="page-content"><p className="muted">{t('users.loadingOne')}</p></section>
  if (error || !value) return <section className="page-content"><p className="alert alert-error">{error ?? t('users.notFound')}</p><Link to="/app/users">{t('users.back')}</Link></section>
  const current = value
  function toggleRole(code: string) { setSelected(current => current.includes(code) ? current.filter(item => item !== code) : [...current, code]) }
  async function saveProfile() { setSaving(true); setError(null); try { const updated = await updateUser(current.id, { displayName, status: current.status }); setValue(updated); setDisplayName(updated.displayName) } catch (cause) { setError(cause instanceof Error ? cause.message : t('users.updateError')) } finally { setSaving(false) } }
  async function changeStatus(status: UserStatus) { setSaving(true); setError(null); try { const updated = await updateUser(current.id, { status }); setValue(updated) } catch (cause) { setError(cause instanceof Error ? cause.message : t('users.statusError')) } finally { setSaving(false) } }
  async function saveRoles() { setSaving(true); setError(null); try { const updated = await replaceUserRoles(current.id, selected); setValue(updated); setSelected(updated.roles) } catch (cause) { setError(cause instanceof Error ? cause.message : t('users.rolesError')) } finally { setSaving(false) } }
  return <section className="page-content"><div className="page-heading"><div><p className="eyebrow">{t('users.title')}</p><h1>{current.displayName}</h1><p className="muted">{current.email}</p></div></div>{error && <p className="alert alert-error">{error}</p>}<div className="card stack-form"><label>{t('users.email')}<input readOnly value={current.email} /></label><label>{t('users.displayName')}<input readOnly={!canUpdate} value={displayName} onChange={event => setDisplayName(event.target.value)} /></label><p>{t('users.status')}: <strong>{current.status}</strong></p><p>{t('organization.created')}: {new Date(current.createdAt).toLocaleString()}</p><p>{t('organization.updated')}: {new Date(current.updatedAt).toLocaleString()}</p>{canUpdate && <div><button type="button" disabled={saving} onClick={() => void saveProfile()}>{t('users.saveDisplayName')}</button>{current.status === 'ACTIVE' ? <button type="button" disabled={saving} onClick={() => void changeStatus('DISABLED')}>{t('users.disable')}</button> : <button type="button" disabled={saving} onClick={() => void changeStatus('ACTIVE')}>{t('users.activate')}</button>}</div>}</div><div className="card"><h2>{t('users.roles')}</h2><div className="stack-form">{roles.map(role => <label key={role.code}><input disabled={!canUpdate} type="checkbox" checked={selected.includes(role.code)} onChange={() => toggleRole(role.code)} /> {role.name}</label>)}{canUpdate && <button type="button" disabled={saving || selected.length === 0} onClick={() => void saveRoles()}>{t('users.saveRoles')}</button>}</div></div><Link to="/app/users">{t('users.back')}</Link></section>
}
